n_epochs : 200
n_splits : 10
batch_size : 16
num_workers : 10
init_lr : 1e-4
final_lr : 1e-6
warmup_lr_init : 1e-6
num_warmup_steps_rate : 0.01
weight_decay : 2e-5
beta :
  - 0.9
  - 0.998
clip_grad_norm : 10
