n_epochs : 200
early_stopping: 10
num_folds: 5
batch_size : 16
init_lr : 1e-4
final_lr : 1e-6
warmup_lr_init : 1e-6
num_warmup_steps_rate : 0.01
weight_decay : 2e-5
beta :
  - 0.9
  - 0.998
clip_grad_norm : 10
accumulation_steps : 1
use_amp: true

hidden_size: 128
nhead: 4
dim_feedforward: 1024

num_tts: 2