n_epochs : 200
early_stopping: 20
num_folds: 5
batch_size : 32
init_lr : 1e-3
final_lr : 1e-5
warmup_lr_init : 1e-5
num_warmup_steps_rate : 0.01
weight_decay : 2e-6
clip_grad_norm : 10
accumulation_steps : 1
use_amp: true

hidden_size: 32
nhead: 2
dim_feedforward: 256

num_tts: 2