version: "3"
services:
  kaggle:
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
    build: .
    volumes:
      - $PWD:/tmp/working
      - ./.py3/root_jupyter:/root/.jupyter # jupyterの設定
    working_dir: /tmp/working
    ports:
      - 8889:8889
    command: jupyter lab --allow-root --ip=0.0.0.0 --port=8889 --no-browser --NotebookApp.token=''
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
