
id: gcn060_001
feats:
  num:
    - duration_episodes #duration
    - genres
    - user_num
    - aired
    - japanese_name
    - other_string
    - string_len
    - implicit_factors
    - implicit_factors_logistic_matrix_factor
    - implicit_factors_bpr
    - multi_hot_features
    - lightgcn_embedding
    - svd_lightgcn_embedding
    - user_num_high_hop_second
    
  cat: []
  models:  []


num_epochs: 1000
early_stopping: 50
lr: 0.002
num_layers: 3
hidden_channels: 64
target_name: score
num_folds : 5