
id: nn033_003
feats:
  num:
    - duration_episodes #duration
    - genres
    - user_num
    - aired
    - japanese_name
    - other_string
    - string_len
    - implicit_factors
    - implicit_factors_logistic_matrix_factor
    - implicit_factors_bpr
    - multi_hot_features
    - lightgcn_embedding
    - user_num_high_hop_second
    
  cat: []
  models:  []


num_epochs: 100
early_stopping: 20
weight_decay: 0.0004287763209553715
dropout_rate: 0.1412633650753899
lr: 0.001
batch_size: 256
hidden_dim: 199
num_layers: 2
target_name: score
num_folds : 5