feats:
  num:
    - duration_episodes #duration
    - genres
    - user_num
    - aired
    - japanese_name
    - other_string
    - string_len
    - implicit_factors_bpr
    - multi_hot_features
  cat: []
  models:  # 学習済みモデルの結果を使う
    - 020_surprise_unseen/d97af2c0 # 1.441 KNNBaseline
    - 020_surprise_unseen/5e4526f8 # 1.442 SVD
    - 020_surprise_unseen/4ed7afa2 # 1.441
    
    
num_epochs: 30
early_stopping: 10

lr: 0.002
batch_size: 256
num_layers: 4
target_name: score
num_folds : 5