
id: nn040_007
feats:
  num:
    - duration_episodes #duration
    - genres
    - user_num
    - aired
    - japanese_name
    - other_string
    - string_len
    - implicit_factors
    - implicit_factors_logistic_matrix_factor
    - implicit_factors_bpr
    - multi_hot_features
  cat: []
  models:  []


num_epochs: 50
early_stopping: 10
weight_decay: 1e-6
dropout_rate: 0.5
lr: 0.002
batch_size: 128
num_layers: 5
target_name: score
num_folds : 5