
id: lgb100_013
feats:
  num:
    - duration_episodes #duration
    - genres
    - user_num
    - aired
    - japanese_name
    - other_string
    - string_len
    - implicit_factors
    - implicit_factors_logistic_matrix_factor
    - implicit_factors_bpr
    - multi_hot_features
  cat:
    - categorical_label_encoded_with_user # categorical_label_encoded
  models: # [] # 学習済みモデルの結果を使う
    - 010_surprise/4b84f9aa # 1.191 SVDpp
    - 010_surprise/277704d6 # 1.203 SVD
    - 010_surprise/bad2980e # 1.202 KNNWithZScore
    - 010_surprise/51c879fa # 1.209 KNNWithMeans
    - 010_surprise/f01160fa # 1.319 KNNBasic
    - 010_surprise/cc507138 # 1.21 BaselineOnly
    - 010_surprise/7027401c # 1.199 SlopeOne
    - 010_surprise/bbcd9cce # 1.319 KNNBasic
    - 010_surprise/ff720d44 # 1.24 CoClustering
    - 000_baseline/8d9ed97c


target_name: score
num_folds : 5

params: 
  objective: regression
  metric: rmse
  verbosity: -1
  boosting_type: gbdt
  learning_rate: 0.02
  num_leaves: 188
  min_child_samples: 60
  max_depth: -1
  bagging_seed: 0
  feature_fraction: 0.93
  bagging_fraction: 0.88
  reg_alpha: 0.009
  reg_lambda: 0.466
  bagging_freq: 4
  max_bin: 200
  device: gpu  # Use GPU