
id: lgb100_016
feats:
  num:
    - duration_episodes #duration
    - genres
    - user_num
    - aired
    - japanese_name
    - other_string
    - string_len
    - implicit_factors
    - implicit_factors_logistic_matrix_factor
    - implicit_factors_bpr
    - multi_hot_features
  cat:
    - categorical_label_encoded_with_user # categorical_label_encoded
  models: [] # 学習済みモデルの結果を使う


target_name: score
num_folds : 5

params: 
  objective: regression
  metric: rmse
  verbosity: -1
  boosting_type: gbdt
  learning_rate: 0.02
  num_leaves: 188
  min_child_samples: 60
  max_depth: -1
  bagging_seed: 0
  feature_fraction: 0.93
  bagging_fraction: 0.88
  reg_alpha: 0.009
  reg_lambda: 0.466
  bagging_freq: 4
  max_bin: 200
  device: gpu  # Use GPU