# ここから features/create.py を破壊的に置き換え
id: lgb200_031

feats:
  num:
    - duration_episodes #duration
    - genres
    - user_num
    - aired
    - japanese_name
    - other_string
    - string_len
    - implicit_factors
    - implicit_factors_logistic_matrix_factor
    - implicit_factors_bpr
    - multi_hot_features
    - lightgcn_embedding
    - svd_lightgcn_embedding
    - user_num_high_hop_second
  cat:
    - categorical_label_encoded # categorical_label_encoded_with_user
  models: [] # 学習済みモデルの結果を使う

target_name: score
num_folds : 10

params: 
  objective: regression
  metric: rmse
  verbosity: -1
  boosting_type: gbdt
  learning_rate: 0.01
  num_leaves: 455
  min_child_samples: 100
  max_depth: -1
  bagging_seed: 0
  feature_fraction:  0.4940013899320794
  bagging_fraction:  0.8064461585846633
  reg_alpha: 0.0035890288845849996
  reg_lambda: 0.6534787410635157
  max_bin: 200
  bagging_freq: 2
  device: gpu  # Use GPU


#  Value: 1.379876400914117
#  Params: 
#    num_leaves: 455
#    min_child_samples: 100
#    feature_fraction: 0.4940013899320794
#    bagging_fraction: 0.8064461585846633
#    reg_alpha: 0.0035890288845849996
#    reg_lambda: 0.6534787410635157
#    bagging_freq: 2